# lightning.pytorch==2.1.0
trainer:
  accelerator: auto
  strategy: ddp
  devices: "0,1" # Single GPU: 0, Multi-GPU: 0,1
  num_nodes: 1
  precision: 32
  enable_checkpointing: true
  enable_progress_bar: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: valid/loss
        mode: min
        save_top_k: -1
        save_last: true
        save_weights_only: true
        filename: '{epoch}-{val/loss:.4f}'
        verbose: true
        dirpath: ckpt
    - class_path: lightning.pytorch.callbacks.RichProgressBar
      init_args:
        refresh_rate: 1
        leave: false
        theme:
          description: green_yellow
          progress_bar: green1
          progress_bar_finished: green1
          progress_bar_pulse: '#6206E0'
          batch_progress: green_yellow
          time: grey82
          processing_speed: grey82
          metrics: grey82
        console_kwargs:
          force_terminal: true
          no_color: false
          width: 200
  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    init_args:
      api_key: w0Npr1BzeXnixD0UOBF6onh5d
      project_name: tssl
      experiment_name: tcrnn_verify
      workspace: rdpi
      save_dir: ./comet_logs
    # - class_path: lightning.pytorch.callbacks.EarlyStopping
    #   init_args:
    #     monitor: val_loss
    #     mode: min
    #     patience: 10
    #     verbose: true
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: true
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  input_dim: 4
  num_classes: 180
  hidden_dim: 64
  lr: 0.0001
  tar_useVAD: true
  ch_mode: MM
  fs: 16000
  method_mode: IDL
  source_num_mode: KNum
  max_num_sources: 1
  return_metric: true
  compile: false
  device: cuda
  lamdba_peochs: 10
data:
  data_dir: /workspaces/tssl/data/
  batch_size:
  - 8
  - 1
  num_workers: 4
ckpt_path: null # /workspaces/tssl/ckpt/pre.ckpt
